#export PATH=/usr/local/bin:$PATH
## virtualenv and virtualenvwrapper
#export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
#export WORKON_HOME=$HOME/.virtualenvs
#source /usr/local/bin/virtualenvwrapper.sh
